### ISSUE TITLE
java.lang.NoSuchMethodException: Could not find method mpicbg.models.Point.<init>([F)V

### ISSUE THREAD

**Issue by thanujadax** [hanslovsky/em-thickness-estimation#7]
Fiji (up to date) gives this error when I try to run the plug in with default values for a .tif stack. Here is the full trace:

```
java.lang.NoSuchMethodException: Could not find method mpicbg.models.Point.<init>([F)V
There was a problem with the class mpicbg.models.Point which can be found here:
/home/thanuja/programs/Fiji.app/jars/mpicbg-1.0.2.jar
java.lang.NoSuchMethodError: mpicbg.models.Point.<init>([F)V
    at org.janelia.thickness.LocalizedCorrelationFit.estimateFromMatrix(LocalizedCorrelationFit.java:132)
    at org.janelia.thickness.LocalizedCorrelationFit.estimateFromMatrix(LocalizedCorrelationFit.java:53)
    at org.janelia.thickness.LocalizedCorrelationFit.estimateFromMatrix(LocalizedCorrelationFit.java:190)
    at org.janelia.thickness.inference.InferFromMatrix.getMediatedShifts(InferFromMatrix.java:179)
    at org.janelia.thickness.inference.InferFromMatrix.estimateZCoordinates(InferFromMatrix.java:124)
    at org.janelia.thickness.inference.InferFromMatrix.estimateZCoordinates(InferFromMatrix.java:79)
    at org.janelia.thickness.plugin.ZPositionCorrection.run(ZPositionCorrection.java:120)
    at ij.IJ.runUserPlugIn(IJ.java:212)
    at ij.IJ.runPlugIn(IJ.java:176)
    at ij.Executer.runCommand(Executer.java:132)
    at ij.Executer.run(Executer.java:65)
    at java.lang.Thread.run(Thread.java:662)

    at org.janelia.thickness.LocalizedCorrelationFit.estimateFromMatrix(LocalizedCorrelationFit.java:132)
    at org.janelia.thickness.LocalizedCorrelationFit.estimateFromMatrix(LocalizedCorrelationFit.java:53)
    at org.janelia.thickness.LocalizedCorrelationFit.estimateFromMatrix(LocalizedCorrelationFit.java:190)
    at org.janelia.thickness.inference.InferFromMatrix.getMediatedShifts(InferFromMatrix.java:179)
    at org.janelia.thickness.inference.InferFromMatrix.estimateZCoordinates(InferFromMatrix.java:124)
    at org.janelia.thickness.inference.InferFromMatrix.estimateZCoordinates(InferFromMatrix.java:79)
    at org.janelia.thickness.plugin.ZPositionCorrection.run(ZPositionCorrection.java:120)
    at ij.IJ.runUserPlugIn(IJ.java:212)
    at ij.IJ.runPlugIn(IJ.java:176)
    at ij.Executer.runCommand(Executer.java:132)
    at ij.Executer.run(Executer.java:65)
    at java.lang.Thread.run(Thread.java:662)
```

**Comment by thanujadax** [comment]
Could have been due to a jar that I manually installed some time ago. The problem was solved when I used a fresh installation of Fiji.
